### ISSUE TITLE
Audio export functionality

### ISSUE THREAD

**Issue by jasalt** [peterborkuti/anki-addon-glossary#2]
It would be nice to have this script export the linked audio as a html audio element with player controls. For now I did this for the exported html by replacing embedded Anki audio elements `[sound:colloquial]` with following html with my text editor:

``` html
 <audio controls src="colloquial.mp3"></audio><br>
```

Thank's for this work. I used it for returning a vocabulary learning course word log as html http://saltio.la/stuff/vocab-log.

**Comment by peterborkuti** [comment]
Hi Jarkko,

Thank you for your comment. I will try it and will notice you if I do it.

If you have time for it, you can send me pull requests also.

Péter

**Comment by peterborkuti** [comment]
Hi @jasalt 

Sorry for the delay, I had no time for this. Now I done it.

Hope it helps.

Péter
