### ISSUE TITLE
Can you add a way or option to export directly to an TXT document?

### ISSUE THREAD

**Issue by githublyff** [peterborkuti/anki-addon-glossary#3]
Because TXT can be read on TTS in the mobile phone, in the bus, subway and other spare time can listen to learn with headphones, can you add a direct export to the txt document in the way or options?

**Comment by peterborkuti** [comment]
Hi @githublyff 
Anki can export into txt. 

File -> Export -> select Cards in Plain Text as "Export format".
If you need special format, please, specify it with concrete examples.

Thank you
Péter
